-- Vintage Hall — demo seed for supabase/schema.sql
-- Run ONCE in the Supabase SQL Editor AFTER schema.sql.
-- Mirrors src/data/products.ts so client lot ids match DB rows (bids FK needs them).
-- Auction end_time values are relative to seeding time, matching the client's hoursFromNow offsets.

insert into public.products
  (id, icon, category, sale_type, photo, extra_photos, name, era, description,
   price, start_price, current_bid, bid_step, end_time,
   origin, condition_grade, dimensions, weight, rarity, badge, certified)
overriding system value
values
  (1, 'samovar', 'decor', 'shop', 'https://picsum.photos/seed/antique-samovar/600/450', null, '{"uk":"Самовар тульський","en":"Tula Samovar","pl":"Samowar tulski","ru":"Самовар тульский"}'::jsonb, '{"uk":"Кін. XIX ст.","en":"Late 19th c.","pl":"Kon. XIX w.","ru":"Кон. XIX в."}'::jsonb, '{"uk":"Латунний самовар із гравіюванням, у робочому стані.","en":"Brass samovar with engraving, in working condition.","pl":"Mosiężny samowar z grawerunkiem, w stanie sprawnym.","ru":"Латунный самовар с гравировкой, в рабочем состоянии."}'::jsonb, 4200, null, null, null, null, 'Росія', 'Дуже добрий', '32 × 22 см', '2.4 кг', 'common', null, false),
  (2, 'watch', 'decor', 'auction', 'https://picsum.photos/seed/pocket-watch-antique/600/450', null, '{"uk":"Кишеньковий годинник","en":"Pocket Watch","pl":"Zegarek kieszonkowy","ru":"Карманные часы"}'::jsonb, '{"uk":"Поч. XX ст.","en":"Early 20th c.","pl":"Pocz. XX w.","ru":"Нач. XX в."}'::jsonb, '{"uk":"Швейцарський механізм, срібний корпус, на ланцюжку.","en":"Swiss movement, silver case, with chain.","pl":"Szwajcarski mechanizm, srebrna obudowa, na łańcuszku.","ru":"Швейцарский механизм, серебряный корпус, на цепочке."}'::jsonb, null, 5000, 5600, 200, now() + interval '8 hours', 'Швейцарія', 'Добрий, механізм робочий', '5 × 4 см', '85 г', 'rare', 'expert', true),
  (3, 'vase', 'decor', 'shop', 'https://picsum.photos/seed/porcelain-vase/600/450', null, '{"uk":"Фарфорова ваза","en":"Porcelain Vase","pl":"Wazon porcelanowy","ru":"Фарфоровая ваза"}'::jsonb, '{"uk":"1900–1910","en":"1900–1910","pl":"1900–1910","ru":"1900–1910"}'::jsonb, '{"uk":"Ручний розпис, невеликий скол на основі.","en":"Hand-painted, small chip on the base.","pl":"Ręcznie malowany, mały odprysk na podstawie.","ru":"Ручная роспись, небольшой скол на основании."}'::jsonb, 3100, null, null, null, null, 'Україна', 'Добрий, невеликий скол', '28 × 14 см', '900 г', 'common', null, false),
  (4, 'candle', 'decor', 'shop', 'https://picsum.photos/seed/bronze-candle/600/450', null, '{"uk":"Бронзовий підсвічник","en":"Bronze Candlestick","pl":"Świecznik z brązu","ru":"Подсвечник бронзовый"}'::jsonb, '{"uk":"Сер. XIX ст.","en":"Mid-19th c.","pl":"Poł. XIX w.","ru":"Сер. XIX в."}'::jsonb, '{"uk":"Парний, лита бронза, природна патина.","en":"Pair, cast bronze, natural patina.","pl":"Para, lity brąz, naturalna patyna.","ru":"Парный, литая бронза, естественная патина."}'::jsonb, 2400, null, null, null, null, 'Франція', 'Дуже добрий', '24 × 9 см (пара)', '1.1 кг', 'common', null, false),
  (5, 'mirror', 'decor', 'shop', 'https://picsum.photos/seed/framed-mirror/600/450', null, '{"uk":"Дзеркало в рамі","en":"Framed Mirror","pl":"Zwierciadło w ramie","ru":"Зеркало в раме"}'::jsonb, '{"uk":"Кін. XIX ст.","en":"Late 19th c.","pl":"Kon. XIX w.","ru":"Кон. XIX в."}'::jsonb, '{"uk":"Різьблена дерев''яна рама, позолота частково збережена.","en":"Carved wooden frame, gilding partially preserved.","pl":"Rzeźbiona drewniana rama, częściowo zachowane złocenie.","ru":"Резная деревянная рама, позолота частично сохранена."}'::jsonb, 5600, null, null, null, null, 'Україна', 'Добрий, часткова втрата позолоти', '70 × 50 см', '4.2 кг', 'rare', 'premium', false),
  (6, 'box', 'decor', 'shop', 'https://picsum.photos/seed/jewelry-box/600/450', null, '{"uk":"Скринька для прикрас","en":"Jewelry Box","pl":"Szkatułka na biżuterię","ru":"Шкатулка для украшений"}'::jsonb, '{"uk":"1920-ті","en":"1920s","pl":"Lata 20. XX w.","ru":"1920-е"}'::jsonb, '{"uk":"Дерево та інкрустація перламутром, із замочком.","en":"Wood with mother-of-pearl inlay, with a small lock.","pl":"Drewno z inkrustacją macicą perłową, z zameczkiem.","ru":"Дерево и инкрустация перламутром, с замочком."}'::jsonb, 1900, null, null, null, null, 'Україна', 'Дуже добрий', '18 × 12 × 8 см', '650 г', 'common', null, false),
  (7, 'coin', 'numismatics', 'auction', 'https://picsum.photos/seed/ruble-nicholas/600/450', null, '{"uk":"Рубль Миколи II","en":"Nicholas II Ruble","pl":"Rubel Mikołaja II","ru":"Рубль Николая II"}'::jsonb, '{"uk":"1898 р.","en":"1898","pl":"1898","ru":"1898 г."}'::jsonb, '{"uk":"Срібло 900-ї проби, збереженість XF.","en":"900 silver, XF condition.","pl":"Srebro próby 900, stan XF.","ru":"Серебро 900-й пробы, сохранность XF."}'::jsonb, null, 3000, 3750, 150, now() + interval '30 hours', 'Російська імперія', 'XF', 'Ø 33.6 мм', '20 г', 'rare', 'expert', true),
  (8, 'coin', 'numismatics', 'shop', 'https://picsum.photos/seed/ussr-ruble/600/450', null, '{"uk":"Ювілейний рубль СРСР","en":"USSR Commemorative Ruble","pl":"Rubel jubileuszowy ZSRR","ru":"Юбилейный рубль СССР"}'::jsonb, '{"uk":"1965 р.","en":"1965","pl":"1965","ru":"1965 г."}'::jsonb, '{"uk":"«20 років Перемоги», без патини, штемпельний блиск.","en":"“20 Years of Victory”, no patina, mint luster.","pl":"„20 lat Zwycięstwa”, bez patyny, blask stemplowy.","ru":"«20 лет Победы», без патины, штемпельный блеск."}'::jsonb, 850, null, null, null, null, 'СРСР', 'UNC', 'Ø 31 мм', '12.8 г', 'common', null, false),
  (9, 'coin', 'numismatics', 'auction', 'https://picsum.photos/seed/poltina-coin/600/450', null, '{"uk":"Монета-полтина","en":"Poltina Coin","pl":"Moneta połtina","ru":"Монета-полтина"}'::jsonb, '{"uk":"1924 р.","en":"1924","pl":"1924","ru":"1924 г."}'::jsonb, '{"uk":"Срібло, перші радянські випуски, добрий стан.","en":"Silver, early Soviet issue, good condition.","pl":"Srebro, pierwsze emisje sowieckie, dobry stan.","ru":"Серебро, первые советские выпуски, хорошее состояние."}'::jsonb, null, 1200, 1400, 100, now() + interval '76 hours', 'СРСР', 'VF', 'Ø 26.7 мм', '10 г', 'rare', null, true),
  (10, 'watch', 'special', 'request', 'https://picsum.photos/seed/mantel-clock/600/450', null, '{"uk":"Французький камінний годинник","en":"French Mantel Clock","pl":"Francuski zegar kominkowy","ru":"Каминные часы французские"}'::jsonb, '{"uk":"Сер. XIX ст.","en":"Mid-19th c.","pl":"Poł. XIX w.","ru":"Сер. XIX в."}'::jsonb, '{"uk":"Бронза і мармур, механізм з боєм, єдиний екземпляр в наявності.","en":"Bronze and marble, striking movement, one-of-a-kind piece in stock.","pl":"Brąz i marmur, mechanizm z biciem, jedyny egzemplarz w magazynie.","ru":"Бронза и мрамор, механизм с боем, единственный экземпляр в наличии."}'::jsonb, null, null, null, null, null, 'Франція', 'Експертний стан', '38 × 24 × 16 см', '6.5 кг', 'unique', 'museum', true),
  (11, 'mirror', 'special', 'request', 'https://picsum.photos/seed/walnut-suite/600/450', null, '{"uk":"Гарнітур з горіха","en":"Walnut Suite","pl":"Komplet orzechowy","ru":"Гарнитур из ореха"}'::jsonb, '{"uk":"1880-ті","en":"1880s","pl":"Lata 80. XIX w.","ru":"1880-е"}'::jsonb, '{"uk":"Стіл і чотири стільці, авторська робота, провенанс підтверджено.","en":"Table and four chairs, signed work, provenance confirmed.","pl":"Stół i cztery krzesła, praca autorska, potwierdzona proweniencja.","ru":"Стол и четыре стула, авторская работа, провенанс подтверждён."}'::jsonb, null, null, null, null, null, 'Україна', 'Реставровано фахово', 'Стіл 120×80 см + 4 стільці', '—', 'unique', 'museum', true),
  (12, 'figurine', 'porcelain', 'shop', '/images/products/little-hostess-pair.jpg', array['/images/products/little-hostess-mark.jpg'], '{"uk":"Парні статуетки «Маленька хазяйка»","en":"Pair of \"Little Hostess\" Figurines","pl":"Para figurek „Mała Gospodyni”","ru":"Парные статуэтки «Маленькая хозяйка»"}'::jsonb, '{"uk":"1958 р.","en":"1958","pl":"1958","ru":"1958 г."}'::jsonb, '{"uk":"Фарфорові статуетки узбечок із чайником, Дулевський завод, скульптор О. М. Богданова. На дні — заводське клеймо та маркування «2С-58г», що підтверджує рік випуску. Яскравий ручний розпис із золоченням, парний комплект у гарному стані.","en":"Porcelain figurines of Uzbek girls with teapots, Dulevo Factory, sculptor O. M. Bogdanova. The base bears the factory mark and \"2С-58г\" code confirming the year of production. Bright hand-painted decoration with gilding, a matched pair in good condition.","pl":"Porcelanowe figurki uzbeckich dziewczynek z czajnikami, fabryka Dulewo, autorstwa O. M. Bogdanowej. Na spodzie widoczny znak fabryczny oraz kod „2С-58г” potwierdzający rok produkcji. Jaskrawe, ręcznie malowane zdobienia ze złoceniem, kompletna para w dobrym stanie.","ru":"Фарфоровые статуэтки узбечек с чайником, Дулёвский завод, скульптор О. М. Богданова. На дне — заводское клеймо и маркировка «2С-58г», подтверждающая год выпуска. Яркая ручная роспись с золочением, парный комплект в хорошем состоянии."}'::jsonb, 5000, null, null, null, null, 'СРСР', 'Дуже добрий', '16 × 11 см (кожна)', '420 г (пара)', 'rare', 'certified', true),
  (13, 'painting', 'painting', 'shop', 'https://picsum.photos/seed/steppe-painting/600/450', null, '{"uk":"Степовий пейзаж","en":"Steppe Landscape","pl":"Pejzaż stepowy","ru":"Степной пейзаж"}'::jsonb, '{"uk":"Кін. XIX ст.","en":"Late 19th c.","pl":"Kon. XIX w.","ru":"Кон. XIX в."}'::jsonb, '{"uk":"Олія, полотно, академічна школа. Підпис художника в правому нижньому куті, авторство атрибутовано експертом галереї.","en":"Oil on canvas, academic school. Artist''s signature in the lower right corner, attribution confirmed by a gallery expert.","pl":"Olej na płótnie, szkoła akademicka. Podpis artysty w prawym dolnym rogu, autorstwo potwierdzone przez eksperta galerii.","ru":"Масло, холст, академическая школа. Подпись художника в правом нижнем углу, авторство атрибутировано экспертом галереи."}'::jsonb, 8500, null, null, null, null, 'Україна', 'Добра, кракелюр лаку', '54 × 38 см (у рамі)', '1.8 кг', 'rare', 'expert', true),
  (14, 'medal', 'militaria', 'auction', 'https://picsum.photos/seed/militaria-badge/600/450', null, '{"uk":"Нагрудний знак, період ПМВ","en":"WWI-era Breast Badge","pl":"Odznaka z okresu I wojny światowej","ru":"Нагрудный знак периода ПМВ"}'::jsonb, '{"uk":"1914–1918","en":"1914–1918","pl":"1914–1918","ru":"1914–1918"}'::jsonb, '{"uk":"Емалевий нагрудний знак австро-угорської армії. Потертості емалі відповідають віку, без реставрації.","en":"Enamel breast badge of the Austro-Hungarian army. Enamel wear consistent with age, no restoration.","pl":"Emaliowana odznaka armii austro-węgierskiej. Przetarcia emalii zgodne z wiekiem, bez renowacji.","ru":"Эмалевый нагрудный знак австро-венгерской армии. Потёртости эмали соответствуют возрасту, без реставрации."}'::jsonb, null, 1800, 1950, 100, now() + interval '130 hours', 'Австро-Угорщина', 'Добрий, потертості емалі', '4.5 × 3 см', '18 г', 'rare', null, false),
  (15, 'ring', 'jewelry', 'shop', 'https://picsum.photos/seed/silver-brooch/600/450', null, '{"uk":"Срібна брошка з бірюзою","en":"Silver Brooch with Turquoise","pl":"Srebrna broszka z turkusem","ru":"Серебряная брошь с бирюзой"}'::jsonb, '{"uk":"Поч. XX ст.","en":"Early 20th c.","pl":"Pocz. XX w.","ru":"Нач. XX в."}'::jsonb, '{"uk":"Срібло 875-ї проби, авторська філігрань, природна бірюза без обробки.","en":"875 silver, signed filigree work, natural untreated turquoise.","pl":"Srebro próby 875, autorska filigran, naturalny, nieobrobiony turkus.","ru":"Серебро 875-й пробы, авторская филигрань, природная бирюза без обработки."}'::jsonb, 3200, null, null, null, null, 'Україна', 'Дуже добрий', '5 × 3 см', '14 г', 'unique', 'certified', true)
on conflict (id) do nothing;

-- keep the identity counter above the seeded ids
select setval(pg_get_serial_sequence('public.products', 'id'), (select max(id) from public.products));

-- realtime for live bidding (safe to re-run)
do $$
begin
  alter publication supabase_realtime add table public.bids;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.products;
exception when duplicate_object then null;
end $$;

